### ISSUE TITLE
Identity creation with Notabene fails using new camera mode

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/notabene#3]
**Bug Description**
Creating an identity with Notabene fails when using the new camera mode for selfies.
It is possible to use the old "basic camera mode" in which case it works.

_The new camera mode is not available on all devices/iOS-versions_, but I am unsure about which.

The resulting photos have **different aspect ratios** and **"mirroring"** (one is flipped horizontally) depending on the camera mode. Perhaps that is the issue.

This is what the new camera mode looks like:
<img src="https://user-images.githubusercontent.com/5469652/116402694-053fe400-a82d-11eb-86a6-8f4d2f8126e6.jpeg" height="400" /><img src="https://user-images.githubusercontent.com/5469652/116402716-096c0180-a82d-11eb-835a-7ef27ba7f45e.jpeg" height="400" />
The new camera mode starts as a "Live Broadcast" (left image) in which you take a photo by pressing on the X in the upper left corner. This brings you to the right image, which shows the captured photo (flipped horizontally) with an overlay.

**Steps to Reproduce**
1. Begin identity creation
2. Enter names for initial account + identity
3. Choose Notabene
4. Choose passport or driving license (only two I've tried with) and take a photo of it.
5. Take a selfie using the new camera mode
6. Finish creation and wait till it fails.

**Expected Result**
Identity creation succeeds.

**Actual Result**
Identity creation fails.

**Versions**
- Software Version: 0.1.69
- OS: iOS 14.4.2
- Browser: Brave
- Mobile device, if applicable: iPhone 11 Pro

**Comment by concordium-cl** [comment]
Issue might have been fixed in the newer Onfido SDK 6.7.2. I have asked Notabene to upgrade from SDK 6.3.1 to 6.7.2.

**Comment by concordium-cl** [comment]
Notabene has updated SDK. @Bargsteen, can you please retest?

**Comment by Bargsteen** [comment]
The issue has not been resolved. Also tried reinstalling the app.
The only noticeable difference is that some of the icons have disappeared.
<img src="https://user-images.githubusercontent.com/5469652/116511097-36202780-a8c6-11eb-99b9-202057dbb510.jpeg" width="300" />

**Comment by ajunge** [comment]
Onfido Ticket ID: 198749

**Comment by concordium-cl** [comment]
- When issuing identity after **Onfido update to 6.10.2**, flow still starts selfie in broadcast mode, which lets id issuance fail every time.

- After some rounds of switching to baisc mode, phone uses basic mode as default but that can also switch back at times. Causality is very unclear here, consistent behavior cannot be reproduced  (when changing documents, restarting app, reinstalling app???). 

- It is also quite inconvenient to get out of broadcast mode with waiting times for user where nothing happens.

_Concordium Testnet Wallet v1.0(14)
iPhone 11, iOS 14.5.1
Onfido SDK presumably 6.10.2_

**Comment by concordium-cl** [comment]
See also https://github.com/Concordium/notabene/issues/12

**Comment by concordium-cl** [comment]
Retested after upgrade to **Onfido 6.12.0** 

Broadcast mode still fails. 

_Concordium Testnet Wallet v1.0(14)
iPhone 11, iOS 14.5.1
Onfido SDK presumably 6.12.0_

**Comment by ajunge** [comment]
New Onfido Ticket ID: 232951

**Comment by concordium-cl** [comment]
Note that when identity fails due to broadcast mode, the reason sent by Onfido is "image/source integrity - fake webcam".

**Comment by concordium-cl** [comment]
For more details, see also [Identity verification failure using the default camera mode (broadcast) on iOS](https://support.concordium.software/t/identity-verification-failure-using-the-default-camera-mode-broadcast-on-ios/25/4)

**Comment by concordium-cl** [comment]
Issue is patched by setting `useMultipleSelfieCapture: false`. This does not create a flawless flow but at least identities do not fail by default anymore.

Note that Onfido is upgraded to SDK 6.13.0.

**Comment by Bargsteen** [comment]
Closing this, as it doesn't appear to be an issue any more.
